package pkgCalculadoraVisual;

import java.text.DecimalFormat;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author tecno59
 */
public class Calculadora extends javax.swing.JPanel {
        double FirstNum = 0;
        double SecondNum = 0;
        String Operation = "";
        DecimalFormat formato = new DecimalFormat("#.##"); 

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButCE = new javax.swing.JButton();
        jButDiv = new javax.swing.JButton();
        jButMulti = new javax.swing.JButton();
        jButDelet = new javax.swing.JButton();
        jBut7 = new javax.swing.JButton();
        jBut4 = new javax.swing.JButton();
        jBut1 = new javax.swing.JButton();
        jBut8 = new javax.swing.JButton();
        jBut5 = new javax.swing.JButton();
        jBut9 = new javax.swing.JButton();
        jBut6 = new javax.swing.JButton();
        jButRest = new javax.swing.JButton();
        jButSuma = new javax.swing.JButton();
        jBut2 = new javax.swing.JButton();
        jBut3 = new javax.swing.JButton();
        JButIgual = new javax.swing.JButton();
        jBut0 = new javax.swing.JButton();
        jButPunto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAPantalla = new javax.swing.JTextArea();

        jButCE.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jButCE.setText("CE");
        jButCE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButCE.setOpaque(true);
        jButCE.addActionListener(this::jButCEActionPerformed);

        jButDiv.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jButDiv.setText("/");
        jButDiv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButDiv.addActionListener(this::jButDivActionPerformed);

        jButMulti.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jButMulti.setText("*");
        jButMulti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButMulti.addActionListener(this::jButMultiActionPerformed);

        jButDelet.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jButDelet.setText("<-- ");
        jButDelet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButDelet.addActionListener(this::jButDeletActionPerformed);

        jBut7.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut7.setText("7");
        jBut7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut7.addActionListener(this::jBut7ActionPerformed);

        jBut4.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut4.setText("4");
        jBut4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut4.addActionListener(this::jBut4ActionPerformed);

        jBut1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut1.setText("1");
        jBut1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut1.addActionListener(this::jBut1ActionPerformed);

        jBut8.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut8.setText("8");
        jBut8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut8.addActionListener(this::jBut8ActionPerformed);

        jBut5.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut5.setText("5");
        jBut5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut5.addActionListener(this::jBut5ActionPerformed);

        jBut9.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut9.setText("9");
        jBut9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut9.addActionListener(this::jBut9ActionPerformed);

        jBut6.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut6.setText("6");
        jBut6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut6.addActionListener(this::jBut6ActionPerformed);

        jButRest.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jButRest.setText("-");
        jButRest.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButRest.addActionListener(this::jButRestActionPerformed);

        jButSuma.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jButSuma.setText("+");
        jButSuma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButSuma.addActionListener(this::jButSumaActionPerformed);

        jBut2.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut2.setText("2");
        jBut2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut2.addActionListener(this::jBut2ActionPerformed);

        jBut3.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut3.setText("3");
        jBut3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut3.addActionListener(this::jBut3ActionPerformed);

        JButIgual.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        JButIgual.setText("=");
        JButIgual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButIgual.addActionListener(this::JButIgualActionPerformed);

        jBut0.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jBut0.setText("0");
        jBut0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut0.addActionListener(this::jBut0ActionPerformed);

        jButPunto.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jButPunto.setText(".");
        jButPunto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButPunto.addActionListener(this::jButPuntoActionPerformed);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTAPantalla.setEditable(false);
        jTAPantalla.setColumns(5);
        jTAPantalla.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jTAPantalla.setRows(5);
        jTAPantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTAPantalla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButCE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBut7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBut8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBut9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButRest, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBut4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBut5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBut6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBut2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBut3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(JButIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButCE, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButMulti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButRest, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBut2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBut3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBut0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(JButIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMultiActionPerformed
        FirstNum = Double.parseDouble(this.jTAPantalla.getText());
        Operation = "*";
        this.jTAPantalla.setText("");
    }//GEN-LAST:event_jButMultiActionPerformed

    private void jBut7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut7ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "7");
    }//GEN-LAST:event_jBut7ActionPerformed

    private void jBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut1ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "1");
    }//GEN-LAST:event_jBut1ActionPerformed

    private void jBut0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut0ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText()+"0");
    }//GEN-LAST:event_jBut0ActionPerformed

    private void jBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "2");
    }//GEN-LAST:event_jBut2ActionPerformed

    private void jBut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut3ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "3");
    }//GEN-LAST:event_jBut3ActionPerformed

    private void jBut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut4ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "4");
    }//GEN-LAST:event_jBut4ActionPerformed

    private void jBut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut5ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "5");
    }//GEN-LAST:event_jBut5ActionPerformed

    private void jBut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut6ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "6");
    }//GEN-LAST:event_jBut6ActionPerformed

    private void jBut8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut8ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "8");
    }//GEN-LAST:event_jBut8ActionPerformed

    private void jBut9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut9ActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + "9");
    }//GEN-LAST:event_jBut9ActionPerformed

    private void jButPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPuntoActionPerformed
        this.jTAPantalla.setText(this.jTAPantalla.getText() + ".");
    }//GEN-LAST:event_jButPuntoActionPerformed

    private void jButCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCEActionPerformed
        this.jTAPantalla.setText("");
    }//GEN-LAST:event_jButCEActionPerformed

    private void jButDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDivActionPerformed
        FirstNum = Double.parseDouble(this.jTAPantalla.getText());
        Operation = "/";
        this.jTAPantalla.setText("");
        
    }//GEN-LAST:event_jButDivActionPerformed

    private void jButRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRestActionPerformed
        FirstNum = Double.parseDouble(this.jTAPantalla.getText());
        Operation = "-";
        this.jTAPantalla.setText("");
    }//GEN-LAST:event_jButRestActionPerformed

    private void jButSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSumaActionPerformed
        FirstNum = Double.parseDouble(this.jTAPantalla.getText());
        Operation = "+";
        this.jTAPantalla.setText("");
    }//GEN-LAST:event_jButSumaActionPerformed

    private void JButIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButIgualActionPerformed
        SecondNum = Double.parseDouble(this.jTAPantalla.getText());
        double Res = 0;
        switch(Operation){
        case "+":
        Res = FirstNum + SecondNum;
        break;
        
        case "-":
        Res = FirstNum - SecondNum;
        break;
        
        case "/":
        Res = FirstNum / SecondNum;
        break;
        
        case "*":
        Res = FirstNum * SecondNum;
        break;
    }
        this.jTAPantalla.setText(String.valueOf(formato.format(FirstNum) + Operation)+this.jTAPantalla.getText()+" = " + String.valueOf(formato.format(Res)));
    }//GEN-LAST:event_JButIgualActionPerformed

    private void jButDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDeletActionPerformed
        String ActText = this.jTAPantalla.getText();
        if(ActText.length() > 0){
        String NewText = ActText.substring(0, ActText.length() - 1);
            this.jTAPantalla.setText(NewText);
        }
    }//GEN-LAST:event_jButDeletActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Crea una ventana vacía
                javax.swing.JFrame frame = new javax.swing.JFrame("Calculadora Visual");
                frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

                // Mete tu panel de la calculadora dentro de esa ventana
                frame.add(new Calculadora()); 

                frame.pack(); // Ajusta el tamaño de la ventana al diseño de tu panel
                frame.setLocationRelativeTo(null); // Centra la ventana en la pantalla
                frame.setVisible(true); // Muestra la ventana
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButIgual;
    private javax.swing.JButton jBut0;
    private javax.swing.JButton jBut1;
    private javax.swing.JButton jBut2;
    private javax.swing.JButton jBut3;
    private javax.swing.JButton jBut4;
    private javax.swing.JButton jBut5;
    private javax.swing.JButton jBut6;
    private javax.swing.JButton jBut7;
    private javax.swing.JButton jBut8;
    private javax.swing.JButton jBut9;
    private javax.swing.JButton jButCE;
    private javax.swing.JButton jButDelet;
    private javax.swing.JButton jButDiv;
    private javax.swing.JButton jButMulti;
    private javax.swing.JButton jButPunto;
    private javax.swing.JButton jButRest;
    private javax.swing.JButton jButSuma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAPantalla;
    // End of variables declaration//GEN-END:variables
}
